<?php
/**
 *
 *
 * @author    sfs teams <zfsfs.team@gmail.com>
 * @copyright 2010-2019 (http://www.sfs.tw)
 * @license   http://www.opensource.org/licenses/mit-license.php MIT
 * @link      http://www.sfs.tw
 * Date: 2019/7/20
 * Time: 下午 4:11
 */

namespace Base\Service;

use Laminas\Log\Logger;

class HyLogger extends Logger
{
    private $isHorngyangManager;

    public function __construct($isHorngyangManager, $options = null)
    {
        $this->isHorngyangManager = $isHorngyangManager;
        parent::__construct($options);
    }

    public function info($message, $extra = [])
    {
        $extra['isHorngyangManager'] = $this->isHorngyangManager;
        return parent::info($message, $extra); // TODO: Change the autogenerated stub
    }

    public function crit($message, $extra = [])
    {
        $extra['isHorngyangManager'] = $this->isHorngyangManager;
        return parent::crit($message, $extra); // TODO: Change the autogenerated stub
    }

    public function alert($message, $extra = [])
    {
        $extra['isHorngyangManager'] = $this->isHorngyangManager;
        return parent::alert($message, $extra); // TODO: Change the autogenerated stub
    }

    public function err($message, $extra = [])
    {
        $extra['isHorngyangManager'] = $this->isHorngyangManager;
        return parent::err($message, $extra); // TODO: Change the autogenerated stub
    }

    public function warn($message, $extra = [])
    {
        $extra['isHorngyangManager'] = $this->isHorngyangManager;
        return parent::warn($message, $extra); // TODO: Change the autogenerated stub
    }

    public function notice($message, $extra = [])
    {
        $extra['isHorngyangManager'] = $this->isHorngyangManager;
        return parent::notice($message, $extra); // TODO: Change the autogenerated stub
    }

    public function emerg($message, $extra = [])
    {
        $extra['isHorngyangManager'] = $this->isHorngyangManager;
        return parent::emerg($message, $extra); // TODO: Change the autogenerated stub
    }
}
